version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: simple
    filename: log/cloud-perimeter-scan.log
    maxBytes: 10485760 # 10MB
    backupCount: 5
    encoding: utf8
loggers:
  __main__:
    level: INFO
    handlers: [console, file]
    propagate: no
root:
  level: NOTSET
  handlers: [console]
